apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: nahid0002/three-tier-backend:v1
          ports:
            - containerPort: 3500
          env:
            - name: host
              value: mysql-service
            - name: user
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER
            - name: password
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
            - name: database
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: MYSQL_DATABASE
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort             # changed from clusterIP/None
  selector:
    app: backend
  ports:
    - port: 3500             # internal pod port
      targetPort: 3500       # container port
      nodePort: 31350        # external port on host (choose 30000-32767)
